// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateDatabase'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function GetDatabaseCharsets(arg1) {
  return window['go']['main']['App']['GetDatabaseCharsets'](arg1);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetSchemas(arg1, arg2) {
  return window['go']['main']['App']['GetSchemas'](arg1, arg2);
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTableRowCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableRowCount'](arg1, arg2, arg3);
}

export function GetTableStructure(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableStructure'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTables'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
